### PR TITLE
Finished Deliverable Zero

### PR DESCRIPTION
**Pull request by cdolfi**
## Description of Change

Finished Deliverable 0 -- project description

## Team Name and Contributers

Guthrie Kuckes, Cali Dolfi, Daniel Ruiz, and Kien Nguyen

## Checklist

Before creating your PR, please ensure the following requirements.

### General

- [ ] PR does **not** include irrelevant or hidden files (i.e. `__pycache__`, `.vscode`... etc.)
- [ ] Changes are in the correct folder
- [ ] There are no merge conflicts
- [ ] Commit messages are sensible and descriptive

### Code

- [ ] Implementation matches proposed design
- [ ] Documentation on how to run the code is created/updated
- [ ] Code is legible

### Report

- [ ] Report meets the deliverable criteria
- [ ] Proposal is up to date with latest decisions

### CODE REVIEW

**Comment by guthrie-kuckes** [comment]
Will we be docked points for this assignment or in the future for having multiple commits in a PR?

**Review by gallettilance — COMMENTED** [review]
If you can squash your commits by the end of the day that would be great

**Comment by gallettilance** [comment]
@cdolfi @guthrie-kuckes  Why do you have 2 pdfs here?

**Review by gallettilance — CHANGES_REQUESTED** [review]
@cdolfi @guthrie-kuckes Why do you have 2 pdfs here?

**Comment by gallettilance** [comment]
@cdolfi @guthrie-kuckes Please squash your commits

**Comment by guthrie-kuckes** [comment]
@gallettilance @cdolfi Squashed the commits, sorry for the delay

**Pull request merged**
