### PR TITLE
Added Scrum 03/27

### PR DESCRIPTION
**Pull request by tzcliff**
## Description of Change

Description goes here

## Team Name and Contributers

Team name and list of contributers for this PR goes here.

## Checklist

Before creating your PR, please ensure the following requirements.

### General

- [x] PR does **not** include irrelevant or hidden files (i.e. `__pycache__`, `.vscode`... etc.)
- [x] Changes are in the correct folder
- [x] There are no merge conflicts
- [x] Commit messages are sensible and descriptive

### Code

- [x] Implementation matches proposed design
- [x] Documentation on how to run the code is created/updated
- [x] Code is legible

### Report

- [x] Report meets the deliverable criteria
- [x] Proposal is up to date with latest decisions

### CODE REVIEW

**Comment by rishabnayak** [comment]
please reformat PR to adhere to formatting guidelines specified in my prior email @ztcric

**Comment by ztcric** [comment]
added scrum 04/03

**Comment by tzcliff** [comment]
> email
Not sure which part of our PR doesn't meet the requirement. Our folder's name is now Cambridge_Eviction_Study_Team2

**Comment by tzcliff** [comment]
> please reformat PR to adhere to formatting guidelines specified in my prior email @ztcric

Please take a look at PR #31

**Comment by rishabnayak** [comment]
The idea was to ensure that you fill out the PR template - there are fields in the template which haven't been filled out. That is what I was referring to

**Comment by tzcliff** [comment]
> The idea was to ensure that you fill out the PR template - there are fields in the template which haven't been filled out. That is what I was referring to

I don't really get what you mean by fields not being filled out.
image

Files are in the correct folder. 
No conflicts.

Code is legible.

If none of our PRs gets approved, it is hard for us to maintain the version control as we all forked from this repo.

**Comment by rishabnayak** [comment]
I'm sorry, if you look right above the screenshot you just took, you'd see this - 

image

There's no description, neither is there a contributer list. Again, that is what I was referring to. Quoting my email - "Please ensure to list your **project name** and **PR subject** in the name of the newly opened pull request and ensure to fill out the **PR template** to ensure that your PR is reviewed."

The description and the contributer list are very much part of the PR Template and need to be filled out.

**Comment by tzcliff** [comment]
> I'm sorry, if you look right above the screenshot you just took, you'd see this -
> 
> image
> 
> There's no description, neither is there a contributer list. Again, that is what I was referring to. Quoting my email - "Please ensure to list your **project name** and **PR subject** in the name of the newly opened pull request and ensure to fill out the **PR template** to ensure that your PR is reviewed."
> 
> The description and the contributer list are very much part of the PR Template and need to be filled out.

My bad for this one. Please discard this PR, as our latest PR has been merged. I'll close it.

**Pull request closed without merging**
