### PR TITLE
submit deliverable 0

### PR DESCRIPTION
**Pull request by kaijiez**
## Description of Change

Submitted Deliverable 0

## Team Name and Contributers

Team The Conquistadors
Kaijie Zhou, Janice He, Tommy Lam, Athina Said, Murtaza Moiyadi, Manuja DeSilva

## Checklist

Before creating your PR, please ensure the following requirements.

### General

- [x] PR does **not** include irrelevant or hidden files (i.e. `__pycache__`, `.vscode`... etc.)
- [x] Changes are in the correct folder
- [x] There are no merge conflicts
- [x] Commit messages are sensible and descriptive

### Code

- [x] Implementation matches proposed design
- [x] Documentation on how to run the code is created/updated
- [x] Code is legible

### Report

- [x] Report meets the deliverable criteria
- [x] Proposal is up to date with latest decisions

### CODE REVIEW

**Review by rishabnayak — COMMENTED** [review]
Hey guys, great job on the PR! I did notice that you’re not using all the datasets. Is that just oversight or do you actually not mean to use all the datasets? Additionally I also saw that you omitted a few of the strategic questions that Rep. Elugardo had on the document, specifically relating to land owned by specific agencies - is this because of lack of clear-cut data, or is there another reason?

**Comment by gallettilance** [comment]
@kaijiez ^

**Comment by kaijiez** [comment]
Hi rishabnayak, sorry for the late response. We actually do mean to use all datasets, its an oversight on our part to not include the other ones in the proposal. Also we will attempt to answer all the strategic questions proposed by Rep. Elugardo, sorry for ommitting out in the proposal.

**Comment by rishabnayak** [comment]
No issues, I'll go ahead and merge the PR - looking forward to chatting with you soon!

**Pull request merged**
